const actionType = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT: "LOGOUT",

  //User
  GET_CURRENT: "GET_CURRENT",

  //Cart
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_CART: "REMOVE_CART",
  UPDATE_QUANTITY: "UPDATE_QUANTITY",
  REMOVE_ALL_CART: "REMOVE_ALL_CART",
  //In - De Product
  INCREASE: "INCREASE",
  DECREASE: "DECREASE",

  GET_PRODUCT_BY_ID: "GET_PRODUCT_BY_ID",
  GET_PRODUCT: "GET_PRODUCT",
};
export default actionType;
