export { default as Banner } from "./banner";
export { default as Header } from "./header";
export { default as Slidebar } from "./Sliderbar";
export { default as Navbar } from "./navbar";
export { default as Footer } from "./Footer";
export { default as SliderCate } from "./SliderBarCate";
export { default as Products } from "./Products";
export { default as CustomSlide } from "./CustomSlide";
export { default as TopSeller } from "./TopSeller";
